### ISSUE TITLE
OSError: Can't load config for 'longformer-base-4096/'

### ISSUE THREAD

**Issue by leopardv10** [allenai/longformer#133]
1. I tried to run the code given on the github page but it gave me this error:
2. I have downloaded the pretrained model but I don't know which file should I put it, can anyone tell me?

Traceback (most recent call last):
  File "/home/mist/.local/lib/python3.6/site-packages/transformers/configuration_utils.py", line 373, in get_config_dict
    raise EnvironmentError
OSError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 6, in <module>
    config = LongformerConfig.from_pretrained('longformer-base-4096/') 
  File "/home/mist/.local/lib/python3.6/site-packages/transformers/configuration_utils.py", line 329, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/mist/.local/lib/python3.6/site-packages/transformers/configuration_utils.py", line 382, in get_config_dict
    raise EnvironmentError(msg)
OSError: Can't load config for 'longformer-base-4096/'. Make sure that:

- 'longformer-base-4096/' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'longformer-base-4096/' is the correct path to a directory containing a config.json file

**Comment by mmoya01** [comment]
my guess is you need to download/untar the pretrained model. You could try

```python
import tarfile
import requests

from longformer.longformer import LongformerConfig

#download longformer-base-4096.tar.gz 
fname = 'longformer-base-4096.tar.gz'
url = 'https://ai2-s2-research.s3-us-west-2.amazonaws.com/longformer/' + fname
r = requests.get(url)
open(fname , 'wb').write(r.content)

#untar longformer-base-4096.tar.gz 
tar = tarfile.open(fname)
tar.extractall()
tar.close()

#load config
config = LongformerConfig.from_pretrained('longformer-base-4096/') 
```
