### ISSUE TITLE
Longformer is not converted to ONNX format.

### ISSUE THREAD

**Issue by vgavrilo** [allenai/longformer#135]
I added to the running model script from https://github.com/allenai/longformer/blob/master/README.md the conversion of the Longformer model to ONNX format:
```python
import torch
from longformer.longformer import Longformer, LongformerConfig
from longformer.sliding_chunks import pad_to_window_size
from transformers import RobertaTokenizer

config = LongformerConfig.from_pretrained('longformer-base-4096/') 
# choose the attention mode 'n2', 'tvm' or 'sliding_chunks'
# 'n2': for regular n2 attantion
# 'tvm': a custom CUDA kernel implementation of our sliding window attention
# 'sliding_chunks': a PyTorch implementation of our sliding window attention
config.attention_mode = 'sliding_chunks'

model = Longformer.from_pretrained('longformer-base-4096/', config=config)
tokenizer = RobertaTokenizer.from_pretrained('roberta-base')
tokenizer.model_max_length = model.config.max_position_embeddings

SAMPLE_TEXT = ' '.join(['Hello world! '] * 1000)  # long input document

input_ids = torch.tensor(tokenizer.encode(SAMPLE_TEXT)).unsqueeze(0)  # batch of size 1

# TVM code doesn't work on CPU. Uncomment this if `config.attention_mode = 'tvm'`
# model = model.cuda(); input_ids = input_ids.cuda()

# Attention mask values -- 0: no attention, 1: local attention, 2: global attention
attention_mask = torch.ones(input_ids.shape, dtype=torch.long, device=input_ids.device) # initialize to local attention
attention_mask[:, [1, 4, 21,]] =  2  # Set global attention based on the task. For example,
                                     # classification: the <s> token
                                     # QA: question tokens

# padding seqlen to the nearest multiple of 512. Needed for the 'sliding_chunks' attention
input_ids, attention_mask = pad_to_window_size(
        input_ids, attention_mask, config.attention_window[0], tokenizer.pad_token_id)

outputs = model(input_ids, attention_mask=attention_mask)
model_onnx_path = "model.onnx"
dummy_input = (input_ids, attention_mask)
torch.onnx.export(model, dummy_input, model_onnx_path)
```
This script was named `run.py`.

Before it, I did
```sh
$ git lfs clone https://github.com/allenai/longformer
$ cd longformer
$ wget https://ai2-s2-research.s3-us-west-2.amazonaws.com/longformer/longformer-base-4096.tar.gz
$ wget https://ai2-s2-research.s3-us-west-2.amazonaws.com/longformer/longformer-large-4096.tar.gz
$ tar xvzf longformer-base-4096.tar.gz
$ tar xvzf longformer-large-4096.tar.gz
$ pip3 install transformers
```
Next, I put the script `run.py` into the directory `longformer`, and ran it. I got the following error:
```sh
/home/user/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/user/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/user/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/user/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/user/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/user/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/user/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/user/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/user/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/user/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/user/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/user/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/user/.local/lib/python3.6/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
/home/user/Longformer/longformer/longformer/longformer.py:115: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if max_num_extra_indices_per_batch <= 0:
/home/user/Longformer/longformer/longformer/longformer.py:139: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert embed_dim == self.embed_dim
/home/user/Longformer/longformer/longformer/sliding_chunks.py:45: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert seqlen % (w * 2) == 0
/home/user/Longformer/longformer/longformer/sliding_chunks.py:46: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert q.size() == k.size()
/home/user/Longformer/longformer/longformer/diagonaled_mm_tvm.py:319: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  beginning_mask = beginning_mask[:, :seq_len].expand(beginning_input.size())
/home/user/Longformer/longformer/longformer/diagonaled_mm_tvm.py:323: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ending_mask = ending_mask[:, -seq_len:].expand(ending_input.size())
/home/user/Longformer/longformer/longformer/longformer.py:177: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert list(attn_weights.size())[:3] == [bsz, seq_len, self.num_heads]
/home/user/Longformer/longformer/longformer/longformer.py:178: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert attn_weights.size(dim=3) in [self.attention_window * 2 + 1, self.attention_window * 3]
/home/user/Longformer/longformer/longformer/longformer.py:201: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  selected_attn_probs = attn_probs.narrow(-1, 0, max_num_extra_indices_per_batch)
/home/user/Longformer/longformer/longformer/longformer.py:207: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  attn_probs = attn_probs.narrow(-1, max_num_extra_indices_per_batch, attn_probs.size(-1) - max_num_extra_indices_per_batch).contiguous()
/home/user/Longformer/longformer/longformer/sliding_chunks.py:92: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert seqlen % (w * 2) == 0
/home/user/Longformer/longformer/longformer/sliding_chunks.py:93: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert prob.size()[:3] == v.size()[:3]
/home/user/Longformer/longformer/longformer/sliding_chunks.py:94: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert prob.size(3) == 2 * w + 1
/home/user/Longformer/longformer/longformer/sliding_chunks.py:19: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  x = x[:, :, :-M]  # B x C x ML+MM
/home/user/Longformer/longformer/longformer/longformer.py:220: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert list(attn.size()) == [bsz, seq_len, self.num_heads, self.head_dim]
/home/user/Longformer/longformer/longformer/longformer.py:238: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert list(attn_weights.size()) == [bsz * self.num_heads, max_num_extra_indices_per_batch, seq_len]
/home/user/Longformer/longformer/longformer/longformer.py:251: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert list(selected_attn.size()) == [bsz * self.num_heads, max_num_extra_indices_per_batch, self.head_dim]
/home/user/Longformer/longformer/longformer/longformer.py:255: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  attn[extra_attention_mask_nonzeros[::-1]] = nonzero_selected_attn.view(len(selection_padding_mask_nonzeros[0]), -1).type_as(hidden_states)
/home/user/.local/lib/python3.6/site-packages/transformers/modeling_utils.py:1645: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  input_tensor.shape == tensor_shape for input_tensor in input_tensors

Traceback (most recent call last):
  File "run.py", line 46, in <module>
    torch.onnx.export(model, dummy_input, model_onnx_path)
  File "/home/user/.local/lib/python3.6/site-packages/torch/onnx/__init__.py", line 230, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/user/.local/lib/python3.6/site-packages/torch/onnx/utils.py", line 91, in export
    use_external_data_format=use_external_data_format)
  File "/home/user/.local/lib/python3.6/site-packages/torch/onnx/utils.py", line 639, in _export
    dynamic_axes=dynamic_axes)
  File "/home/user/.local/lib/python3.6/site-packages/torch/onnx/utils.py", line 421, in _model_to_graph
    dynamic_axes=dynamic_axes, input_names=input_names)
  File "/home/user/.local/lib/python3.6/site-packages/torch/onnx/utils.py", line 168, in _optimize_graph
    torch._C._jit_pass_onnx_prepare_inplace_ops_for_onnx(graph)
RuntimeError: Only consecutive 1-d tensor indices are supported in exporting aten::index_put to ONNX.
```

My environment: Ubuntu 18.10 64-bit (x86_64), Python 3.6.8, PyTorch 1.7.0.

**Comment by ibeltagy** [comment]
I am not familiar with ONNX, but looks like it is complaining about a certain pytorch construct. If you point me to it, we can figure out how to implement it differently.

**Comment by samru-rai** [comment]
@ibeltagy Interestingly the issue persists with at least with `sentiment-analysis` pipeline but fails with `feature-extraction` pipeline. I have created a reproducible [collab notebook](https://colab.research.google.com/drive/1b_iKr60Z4ENoEv6Qaa2jCI2pt5n1FAi_?usp=sharing#scrollTo=V0rFL6U0CLG-) if you are interested to see it in action.

**Comment by andrei-kochin** [comment]
@ibeltagy do you have any updates on this ticket? can we expect future plans or suggestions soon?

Thank you

**Comment by samru-rai** [comment]
@ibeltagy @andrei-kochin I would also be highly interested to know

**Comment by aditya-malte** [comment]
Hi @ibeltagy ,
Have we found any solution to this problem. ONNX especially needed for Longformer as the model is pretty huge.
Thanks

**Comment by ibeltagy** [comment]
I am not familiar with ONNX, so I am not sure what the problem is. Looks like it is complaining about a certain operation the model is using? @aditya-malte, can you say more about what the problem is?

**Comment by aditya-malte** [comment]
Hi @ibeltagy,
Thanks for the quick reply. I tried finding a fix for the error, but I’m not really well versed with ONNX so started reading up on it. With that being said, at the moment I don’t really have much knowledge on how to solve. So thought of asking the same.

**Comment by andrei-kochin** [comment]
@ibeltagy some way to replicate issue was provided in earlier comment https://github.com/allenai/longformer/issues/135#issuecomment-751998000

Have you managed to try?

**Comment by ibeltagy** [comment]
@andrei-kochin, we don't have plans to address this issue, and I don't really know much about ONNX. However, if you explain the pytorch construct that is not supported by ONNX, I might be able to suggest a different way to implement it.

**Comment by liyaxin999** [comment]
@ibeltagy I have similar issues with converting the model to ONNX, I converted the model to ONNX model,  but when I tried to infer with onnxruntime I got ScatterND  error while session run. I am guessing there are some operations not supported by onnx.
Here are some[ onnx unsupported implementations](https://pytorch.org/docs/stable/onnx.html#unsupported-tensor-indexing-patterns), if you could find ways to avoid them, it would be very helfpul.

**Comment by sevenold** [comment]
@liyaxin999 Did you solve it ?

**Comment by liyaxin999** [comment]
> 

no, but now huggingface has longformer and it can be exported to onnx. see [here](https://huggingface.co/docs/transformers/serialization)

**Comment by liyaxin999** [comment]
> @liyaxin999 Did you solve it ?
no, but huggingface has longformer now, and it can be exported to onnx. see [here](https://huggingface.co/docs/transformers/serialization)
