### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [12, 4096, 1]], which is output 0

### ISSUE THREAD

**Issue by Herais** [allenai/longformer#201]
I had a problemwhile Finetuning LED for Summarization Task in Colab, with the following error message:
------------------
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [12, 4096, 1]], which is output 0 of ViewBackward, is at version 2; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
--------------------
The Settings for the Training are as follow:

Training Set: 17 Samples, each with less than 4000 tokens.
As for environment, I ran !pip install -r requirements.txt, where requirements come from the latest master branch of longformer.
transformers @ git+http://github.com/ibeltagy/transformers.git@longformer_encoder_decoder#egg=transformers
pytorch-lightning @ git+http://github.com/ibeltagy/pytorch-lightning.git@v0.8.5_fixes#egg=pytorch-lightning
torch>=1.6.0
tensorboardX
test-tube==0.7.5
nlp
rouge_score
CUDA for the colab session was:
Sun Jul 18 03:58:07 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.42.01 Driver Version: 460.32.03 CUDA Version: 11.2 |
|-------------------------------+----------------------+----------------------+
| GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr. ECC |
| Fan Temp Perf Pwr:Usage/Cap| Memory-Usage | GPU-Util Compute M. |
| | | MIG M. |
|===============================+======================+======================|
| 0 Tesla P100-PCIE... Off | 00000000:00:04.0 Off | 0 |
| N/A 44C P0 30W / 250W | 0MiB / 16280MiB | 0% Default |
| | | N/A |
+-------------------------------+----------------------+----------------------+
+-----------------------------------------------------------------------------+
| Processes: |
| GPU GI CI PID Type Process name GPU Memory |
| ID ID Usage |
|=============================================================================|
| No running processes found |
+-----------------------------------------------------------------------------+

Other Training Configurations are as follow:

loaded from pretrained is the "allenai/led-base-16384" with HuggingFace.

max_input_length = 4096
min_output_length = 256
max_output_length = 512
batch_size = 2

set generate hyperparameters
led.config.encoder_layers=6
led.config.decoder_layers=6
led.config.attention_window=128 # left and right so total 256
led.config.num_beams = 2
led.config.length_penalty = 2.0
led.config.early_stopping = True
led.config.no_repeat_ngram_size = 3

adjust output length according to training and val datasets
led.config.max_length = max_output_length # now at 256
led.config.min_length = min_output_length # now at 512

enable fp16 apex training
training_args = Seq2SeqTrainingArguments(
predict_with_generate=True,
evaluation_strategy="epoch",
per_device_train_batch_size=batch_size,
per_device_eval_batch_size=batch_size,
fp16=True,
output_dir=path_models,
logging_steps=5,
eval_steps=10,
save_steps=10,
save_total_limit=4,
load_best_model_at_end=True,
gradient_accumulation_steps=4,
num_train_epochs=6,
)

trainer = Seq2SeqTrainer(
model=led,
tokenizer=tokenizer,
args=training_args,
compute_metrics=compute_metrics,
train_dataset=train_dataset,
eval_dataset=val_dataset,
)

Enabling "torch.autograd.set_detect_anomaly(True)", point to the following:

/led/modeling_led.py", line 589, in _compute_attn_output_with_global_indices
attn_probs_only_global.transpose(1, 2), value_vectors_only_global.transpose(1, 2)
----------------------------------------------------
Going to modeling_led.py, the above line is from the " def _compute_attn_output_with_global_indices"
---------------------
    def _compute_attn_output_with_global_indices(
        self,
        value_vectors,
        attn_probs,
        max_num_global_attn_indices,
        is_index_global_attn_nonzero,
        is_local_index_global_attn_nonzero,
    ):
        batch_size = attn_probs.shape[0]

        # cut local attn probs to global only
        attn_probs_only_global = attn_probs.narrow(-1, 0, max_num_global_attn_indices)
        # get value vectors for global only
        value_vectors_only_global = value_vectors.new_zeros(
            batch_size, max_num_global_attn_indices, self.num_heads, self.head_dim
        )
        value_vectors_only_global[is_local_index_global_attn_nonzero] = value_vectors[is_index_global_attn_nonzero]

        # use `matmul` because `einsum` crashes sometimes with fp16
        # attn = torch.einsum('blhs,bshd->blhd', (selected_attn_probs, selected_v))
        # compute attn output only global
        attn_output_only_global = torch.matmul(
            attn_probs_only_global.transpose(1, 2), value_vectors_only_global.transpose(1, 2)
        ).transpose(1, 2)

        # reshape attn probs
        attn_probs_without_global = attn_probs.narrow(
            -1, max_num_global_attn_indices, attn_probs.size(-1) - max_num_global_attn_indices
        ).contiguous()

        # compute attn output with global
        attn_output_without_global = self._sliding_chunks_matmul_attn_probs_value(
            attn_probs_without_global, value_vectors, self.one_sided_attn_window_size
        )
        return attn_output_only_global + attn_output_without_global
=========================

It seems that the global attention calculation made changes to torch and somehow created some conflicts with gradient computation in terms tracking steps, is there a way to avoid this from happening?

I had successfully trained larger samples (600+ samples) with up to 8192 input tokens, with generate length between 256 and 512 , attention window size = 512 (1024 total from both side), using the led-base checkpoint. So seeing this error message is a bit frustrating. Any help is highly appreciated. Let me know if you need more information. Thank you.

------------------------
***** Running training *****
Num examples = 17
Num Epochs = 6
Instantaneous batch size per device = 2
Total train batch size (w. parallel, distributed & accumulation) = 8
Gradient Accumulation steps = 4
Total optimization steps = 12
[ 3/12 00:06 < 00:57, 0.16 it/s, Epoch 0.89/6]
Epoch Training Loss Validation Loss
/usr/local/lib/python3.7/dist-packages/torch/autograd/init.py:149: UserWarning: Error detected in BmmBackward0. Traceback of forward call that caused the error:
File "/usr/local/lib/python3.7/dist-packages/torch/autograd/function.py", line 87, in apply
return self._forward_cls.backward(self, *args) # type: ignore[attr-defined]
File "/usr/local/lib/python3.7/dist-packages/torch/utils/checkpoint.py", line 122, in backward
outputs = ctx.run_function(*detached_inputs)
File "/usr/local/lib/python3.7/dist-packages/transformers/models/led/modeling_led.py", line 1816, in custom_forward
return module(*inputs, is_global_attn, output_attentions)
File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
return forward_call(*input, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/transformers/models/led/modeling_led.py", line 915, in forward
output_attentions=output_attentions,
File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
return forward_call(*input, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/transformers/models/led/modeling_led.py", line 726, in forward
output_attentions=output_attentions,
File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
return forward_call(*input, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/transformers/models/led/modeling_led.py", line 282, in forward
is_local_index_global_attn_nonzero=is_local_index_global_attn_nonzero,
File "/usr/local/lib/python3.7/dist-packages/transformers/models/led/modeling_led.py", line 589, in _compute_attn_output_with_global_indices
attn_probs_only_global.transpose(1, 2), value_vectors_only_global.transpose(1, 2)
(Triggered internally at /pytorch/torch/csrc/autograd/python_anomaly_mode.cpp:104.)
allow_unreachable=True, accumulate_grad=True) # allow_unreachable flag
/usr/local/lib/python3.7/dist-packages/torch/autograd/init.py:149: UserWarning:

Previous calculation was induced by CheckpointFunctionBackward. Traceback of forward call that induced the previous calculation:
File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"main", mod_spec)
File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py", line 16, in
app.launch_new_instance()
File "/usr/local/lib/python3.7/dist-packages/traitlets/config/application.py", line 845, in launch_instance
app.start()
File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelapp.py", line 499, in start
self.io_loop.start()
File "/usr/local/lib/python3.7/dist-packages/tornado/platform/asyncio.py", line 132, in start
self.asyncio_loop.run_forever()
File "/usr/lib/python3.7/asyncio/base_events.py", line 541, in run_forever
self._run_once()
File "/usr/lib/python3.7/asyncio/base_events.py", line 1786, in _run_once
handle._run()
File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
self._context.run(self._callback, *self._args)
File "/usr/local/lib/python3.7/dist-packages/tornado/platform/asyncio.py", line 122, in _handle_events
handler_func(fileobj, events)
File "/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
return fn(*args, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 451, in _handle_events
self._handle_recv()
File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
self._run_callback(callback, msg)
File "/usr/local/lib/python3.7/dist-packages/zmq/eventloop/zmqstream.py", line 434, in _run_callback
callback(*args, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
return fn(*args, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 283, in dispatcher
return self.dispatch_shell(stream, msg)
File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
handler(stream, idents, msg)
File "/usr/local/lib/python3.7/dist-packages/ipykernel/kernelbase.py", line 399, in execute_request
user_expressions, allow_stdin)
File "/usr/local/lib/python3.7/dist-packages/ipykernel/ipkernel.py", line 208, in do_execute
res = shell.run_cell(code, store_history=store_history, silent=silent)
File "/usr/local/lib/python3.7/dist-packages/ipykernel/zmqshell.py", line 537, in run_cell
return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2718, in run_cell
interactivity=interactivity, compiler=compiler, result=result)
File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2828, in run_ast_nodes
if self.run_code(code, result):
File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
exec(code_obj, self.user_global_ns, self.user_ns)
File "", line 1, in
trainer.train()
File "/usr/local/lib/python3.7/dist-packages/transformers/trainer.py", line 1269, in train
tr_loss += self.training_step(model, inputs)
File "/usr/local/lib/python3.7/dist-packages/transformers/trainer.py", line 1762, in training_step
loss = self.compute_loss(model, inputs)
File "/usr/local/lib/python3.7/dist-packages/transformers/trainer.py", line 1794, in compute_loss
outputs = model(**inputs)
File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
return forward_call(*input, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/transformers/models/led/modeling_led.py", line 2362, in forward
return_dict=return_dict,
File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
return forward_call(*input, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/transformers/models/led/modeling_led.py", line 2206, in forward
return_dict=return_dict,
File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
return forward_call(*input, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/transformers/models/led/modeling_led.py", line 1826, in forward
is_index_global_attn,
File "/usr/local/lib/python3.7/dist-packages/torch/utils/checkpoint.py", line 211, in checkpoint
return CheckpointFunction.apply(function, preserve, *args)
(Triggered internally at /pytorch/torch/csrc/autograd/python_anomaly_mode.cpp:109.)
allow_unreachable=True, accumulate_grad=True) # allow_unreachable flag
RuntimeError Traceback (most recent call last)
in ()
----> 1 trainer.train()
2 #resume_from_checkpoint=True

6 frames
/usr/local/lib/python3.7/dist-packages/torch/autograd/init.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables, inputs)
147 Variable.execution_engine.run_backward(
148 tensors, grad_tensors, retain_graph, create_graph, inputs,
--> 149 allow_unreachable=True, accumulate_grad=True) # allow_unreachable flag
150
151

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [12, 4096, 1]], which is output 0 of ViewBackward, is at version 2; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

**Comment by Herais** [comment]
It seems the problem can be fixed by detaching the torch from gradient computation, I hope this does not create further unintended consequences. The changes I made to the modeling_led.py in def _compute_attn_output_with_global_indices functions are as follow:
from

    attn_output_only_global = torch.matmul(
        attn_probs_only_global.transpose(1, 2), value_vectors_only_global.transpose(1, 2)
    ).transpose(1, 2)

to

    attn_output_only_global = torch.matmul(
        attn_probs_only_global.detach().transpose(1, 2), value_vectors_only_global.detach().transpose(1, 2)
    ).transpose(1, 2)
