### ISSUE TITLE
does Gradient checkpointing support multi-gpu ?

### ISSUE THREAD

**Issue by schinger** [allenai/longformer#63]

**Comment by ibeltagy** [comment]
https://github.com/huggingface/transformers/pull/4659

**Comment by ibeltagy** [comment]
The answer is yes, but you need two things (pytroch constraints):
- use `find_unused_parameters=False`
- make sure that all model parameters contribute to the calculation of the loss. 

Here's an example 
```
import os
import torch
from transformers import BertForPreTraining
os.environ['MASTER_ADDR'] = 'localhost'
os.environ['MASTER_PORT'] = '12355'
torch.distributed.init_process_group(backend="nccl", rank=0, world_size=1)

model = BertForPreTraining.from_pretrained('bert-base-uncased').cuda()
model = torch.nn.parallel.DistributedDataParallel(model, find_unused_parameters=True)
outputs = model(torch.tensor([[1, 2, 3]]).cuda())
outputs[0].sum().backward()

# check parameters with no grad
for n, p in model.named_parameters():
    if p.grad is None and p.requires_grad is True:
        print('Parameter not used:', n, p.shape)  # prints unused parameters. Remove them from your model 

outputs = model(torch.tensor([[1, 2, 3]]).cuda())
outputs[0].sum().backward()  # if any unused parameters remain in your model, this will break.  
```

**Comment by Weilin37** [comment]
Hi,

I tried multi-gpu on longformer with a similar setup, and I found some layers that were unused. How do I correct this?

```
No forward parameters: module.longformer.pooler.dense.weight torch.Size([768, 768])
No forward parameters: module.longformer.pooler.dense.bias torch.Size([768])
```

**Comment by ibeltagy** [comment]
would `del p` delete them from the model correctly?

**Comment by Weilin37** [comment]
Unfortunately that did not make a difference

**Comment by ibeltagy** [comment]
how about `p.requires_grad = False`? the other solution is to change the model implementation and remove that parameter from the code.

**Comment by matt-peters** [comment]
Haven't read through the linked thread - but a quick workaround-hack I've employed before adds something like this to forward:

```
for p in self.parameters():
    loss += 0.0 * p.sum()
```

This ensures all parameters have a gradient.  If you know the extra parameters that are causing the problem you can restrict the loop to just those.

**Comment by Weilin37** [comment]
> how about `p.requires_grad = False`? the other solution is to change the model implementation and remove that parameter from the code.

No luck either. Here is part of my implementation, in case I did it wrong:

```
            b_input_ids = batch[0].cuda(gpu)
            b_input_mask = batch[1].cuda(gpu)
            b_labels = batch[2].cuda(gpu)

            model.zero_grad()        

            loss, logits = model(b_input_ids, token_type_ids=None, attention_mask=b_input_mask, labels=b_labels)

            loss = loss.mean()
            total_train_loss += loss.item()

            loss.backward()
            
            # check parameters with no grad
            for n, p in model.named_parameters():
                if p.grad is None and p.requires_grad is True:
                    print('No forward parameters:', n, p.shape)
                    p.requires_grad = False

            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)

            optimizer.step()

            scheduler.step()
```

**Comment by Weilin37** [comment]
> Haven't read through the linked thread - but a quick workaround-hack I've employed before adds something like this to forward:
> 
> ```
> for p in self.parameters():
>     loss += 0.0 * p.sum()
> ```
> 
> This ensures all parameters have a gradient. If you know the extra parameters that are causing the problem you can restrict the loop to just those.

Where would I need to implement this in the training loop?

**Comment by matt-peters** [comment]
In your code right above, add it after the line `loss = loss.mean()` so it looks like:

```
loss = loss.mean()
for p in model.parameters():
    loss += 0.0 * p.sum()
```

**Comment by Weilin37** [comment]
> In your code right above, add it after the line `loss = loss.mean()` so it looks like:
> 
> ```
> loss = loss.mean()
> for p in model.parameters():
>     loss += 0.0 * p.sum()
> ```

I tried it and I think it caused some sort of memory access error. It wasn't able to reach the loss.backward() step. The stack trace is below:

```
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/nn/parallel/_functions.py:61: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
Traceback (most recent call last):
  File "ddp.py", line 202, in <module>
    main()
  File "ddp.py", line 57, in main
    train_model(0, train_dataset = Train_dataset)
  File "ddp.py", line 171, in train_model
    loss.backward()
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/autograd/__init__.py", line 127, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases yet.3) Incorrect unused parameter detection. The return value of the `forward` function is inspected by the distributed data parallel wrapper to figure out if any of the module's parameters went unused. For unused parameters, DDP would not expect gradients from then. However, if an unused parameter becomes part of the autograd graph at a later point in time (e.g., in a reentrant backward when using `checkpoint`), the gradient will show up unexpectedly. If all parameters in the model participate in the backward pass, you can disable unused parameter detection by passing the keyword argument `find_unused_parameters=False` to `torch.nn.parallel.DistributedDataParallel`.
Exception raised from mark_variable_ready at /pytorch/torch/csrc/distributed/c10d/reducer.cpp:452 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f77e524b1e2 in /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: c10d::Reducer::mark_variable_ready(c10d::Reducer::VariableIndex) + 0x909 (0x7f76d65b7239 in /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #2: c10d::Reducer::autograd_hook(c10d::Reducer::VariableIndex) + 0xef (0x7f76d65b950f in /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #3: <unknown function> + 0xa90676 (0x7f76d65b9676 in /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0xa95146 (0x7f76d65be146 in /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #5: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&, std::shared_ptr<torch::autograd::ReadyQueue> const&) + 0x4dd (0x7f76c8cd84dd in /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
frame #6: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&) + 0x451 (0x7f76c8cd9fa1 in /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
frame #7: torch::autograd::Engine::execute_with_graph_task(std::shared_ptr<torch::autograd::GraphTask> const&, std::shared_ptr<torch::autograd::Node>) + 0x25c (0x7f76c8cd759c in /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
frame #8: torch::autograd::python::PythonEngine::execute_with_graph_task(std::shared_ptr<torch::autograd::GraphTask> const&, std::shared_ptr<torch::autograd::Node>) + 0x3c (0x7f76d60568dc in /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #9: torch::autograd::Engine::execute(std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, bool, bool, std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&) + 0x803 (0x7f76c8cd69f3 in /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
frame #10: torch::autograd::python::PythonEngine::execute(std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, bool, bool, std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&) + 0x4e (0x7f76d60566de in /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #11: THPEngine_run_backward(THPEngine*, _object*, _object*) + 0xa54 (0x7f76d60573c4 in /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #29: torch::autograd::PyNode::apply(std::vector<at::Tensor, std::allocator<at::Tensor> >&&) + 0x183 (0x7f76d605e483 in /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #30: <unknown function> + 0x3375bb7 (0x7f76c8cddbb7 in /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
frame #31: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&, std::shared_ptr<torch::autograd::ReadyQueue> const&) + 0x1400 (0x7f76c8cd9400 in /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
frame #32: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&) + 0x451 (0x7f76c8cd9fa1 in /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
frame #33: torch::autograd::Engine::thread_init(int, std::shared_ptr<torch::autograd::ReadyQueue> const&, bool) + 0x89 (0x7f76c8cd2119 in /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
frame #34: torch::autograd::python::PythonEngine::thread_init(int, std::shared_ptr<torch::autograd::ReadyQueue> const&, bool) + 0x4a (0x7f76d60564ba in /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #35: <unknown function> + 0xc819d (0x7f76d749119d in /home/ec2-user/anaconda3/envs/JupyterSystemEnv/bin/../lib/libstdc++.so.6)
frame #36: <unknown function> + 0x7e75 (0x7f77f0a93e75 in /lib64/libpthread.so.0)
frame #37: clone + 0x6d (0x7f77efeab8fd in /lib64/libc.so.6)
```

**Comment by ibeltagy** [comment]
From the error message, 
```
RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases yet.3) Incorrect unused parameter detection. The return value of the `forward` function is inspected by the distributed data parallel wrapper to figure out if any of the module's parameters went unused. For unused parameters, DDP would not expect gradients from then. However, if an unused parameter becomes part of the autograd graph at a later point in time (e.g., in a reentrant backward when using `checkpoint`), the gradient will show up unexpectedly. If all parameters in the model participate in the backward pass, you can disable unused parameter detection by passing the keyword argument `find_unused_parameters=False` to `torch.nn.parallel.DistributedDataParallel`.
```
parameters before the checkpoint call shouldn't be used again. So the loop of `loss += p.sum()` should loop only over the unused parameters. Try something like: 
```
unused_params = [module.longformer.pooler.dense.weight, module.longformer.pooler.dense.bias]
loss = loss.mean()
for p in unused_params:
    loss += 0.0 * p.sum()
```

**Comment by Weilin37** [comment]
I think I got slightly farther but it's giving me the same error. When I try to print the unused parameters, it doesn't print those two layers anymore. But I get the same error and I guess there must be something unused somewhere else:

```
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/nn/parallel/_functions.py:61: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
Traceback (most recent call last):
  File "ddp.py", line 205, in <module>
    main()
  File "ddp.py", line 57, in main
    train_model(0, train_dataset = Train_dataset)
  File "ddp.py", line 164, in train_model
    loss, logits = model(b_input_ids, token_type_ids=None, attention_mask=b_input_mask, labels=b_labels)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 528, in forward
    self.reducer.prepare_for_backward([])
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
```

I am posting my entire train_model() function below as reference:

```
def train_model(gpu, train_dataset):

    dist.init_process_group(backend='nccl', init_method='env://', world_size=1, rank=0) 
    model = LongformerForSequenceClassification.from_pretrained('allenai/longformer-base-4096',
                                                                gradient_checkpointing=True,
                                                                num_labels=4)

    torch.cuda.set_device(gpu)
    model.cuda(gpu)
    
    batch_size = 1 # CHANGE BATCH SIZE HERE
    epochs = 1 # CHANGE NUM EPOCHS HERE
    
    optimizer = AdamW(model.parameters(),
                  lr = 2e-5,
                  eps = 1e-8
                )

    model = nn.parallel.DistributedDataParallel(model, find_unused_parameters=False)
    
    train_sampler = torch.utils.data.distributed.DistributedSampler(train_dataset,
                                                                    num_replicas=1, # World size
                                                                    rank=0) # Only one node, so rank=gpu
    
    train_dataloader = torch.utils.data.DataLoader(dataset=train_dataset,
                                               batch_size=batch_size,
                                               shuffle=False,
                                               num_workers=0,
                                               pin_memory=True,
                                               sampler=train_sampler)

    total_steps = len(train_dataloader) * epochs

    scheduler = get_linear_schedule_with_warmup(optimizer, 
                                            num_warmup_steps = 0,
                                            num_training_steps = total_steps)
    
    for epoch_i in range(epochs):
        total_train_loss = 0
   
        model.train()

        for step, batch in enumerate(train_dataloader):
            b_input_ids = batch[0].cuda(gpu)
            b_input_mask = batch[1].cuda(gpu)
            b_labels = batch[2].cuda(gpu)

            model.zero_grad()        

            loss, logits = model(b_input_ids, token_type_ids=None, attention_mask=b_input_mask, labels=b_labels)

            unused_params = ['module.longformer.pooler.dense.weight', 'module.longformer.pooler.dense.bias']
            loss = loss.mean()
            for n, p in model.named_parameters():
                if n in unused_params:
                    loss += 0.0 * p.sum()
    
            total_train_loss += loss.item()

            loss.backward()
            
            # check parameters with no grad
            for n, p in model.named_parameters():
                if p.grad is None and p.requires_grad is True:
                    print('No forward parameters:', n, p.shape)

            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)

            optimizer.step()

            scheduler.step()
            
```

**Comment by moscow25** [comment]
Thanks @ibeltagy -- and for your minimal example. I also found that for HuggingFace models were I add grad checkpointing -- things work ok if DPP is run with `find_unused_parameters=False` (but fail with that`Expected to mark a variable ready only once...`  error otherwise). 

I'm still a bit shocked that DDP is much slower than DP and with half the per-GPU batch size [when testing 1 GPU only]. Maybe that will improve in the future, but for now happy that grad checkpoint and DDP do work at all, and for multi-GPU. 

According to your test the model I was working with (HuggingFace T5) does *not* have any unused params that expect gradient. But somehow the `find_unused_parameters` check still needs to be turned off, and then things train smoothly.

**Comment by ClaartjeBarkhof** [comment]
Hi, I am trying to use gradient checkpointing in combination with DistributedDataParallel (4 GPUs, 1 node) and weight sharing between different parts of my model.

My model comprises of a few parts:

1. Encoder (Roberta checkpoint)
2. Pooler
3. Decoder (Adapted Roberta checkpoint)
4. Language model head

**Ideally, I would like to share the weights between the Encoder and Decoder**, but I think this does not work in combination with gradient checkpointing and DDP. But I am not entirely sure, as the errors are not always very illustrative.

- When I use **1 GPU** and **no DDP** and **weight sharing**, the gradient checkpointing works fine and increases my batch size from 3 to 20!
- When I use **4 GPUs** and **DDP* and **no weight sharing**, the gradient checkpointing works (with `find_unused_parameters=False` and returning only the `loss` from `forward`) and that allows me to use a batch size of 8 (so effectively 32)
- When I try to **2 GPUs** and **DDP** and **weight sharing**, the following error is thrown:

```
RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 
1) Use of a module parameter outside the forward function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes
2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple checkpoint functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases yet.
3) Incorrect unused parameter detection. The return value of the forward function is inspected by the distributed data parallel wrapper to figure out if any of the module's parameters went unused. For unused parameters, DDP would not expect gradients from then. However, if an unused parameter becomes part of the autograd graph at a later point in time (e.g., in a reentrant backward when using checkpoint), the gradient will show up unexpectedly. If all parameters in the model participate in the backward pass, you can disable unused parameter detection by passing the keyword argument find_unused_parameters=False to torch.nn.parallel.DistributedDataParallel.
```

Does weight sharing fall in category 2 of this Error message?

It would be great to leverage the benefits of **DDP**, **multi-GPU**, **gradient checkpointing** and **weight sharing**, but I am just not sure whether that is possible.

**Comment by zhangxinyu-xyz** [comment]
> Hi, I am trying to use gradient checkpointing in combination with DistributedDataParallel (4 GPUs, 1 node) and weight sharing between different parts of my model.
> 
> My model comprises of a few parts:
> 
>     1. Encoder (Roberta checkpoint)
> 
>     2. Pooler
> 
>     3. Decoder (Adapted Roberta checkpoint)
> 
>     4. Language model head
> 
> 
> Altogether they form a nn.module. But gradient checkpointing can be activated for the Encoder and Decoder separately.
> 
> **Ideally, I would like to share the weights between the Encoder and Decoder**, but I think this does not work in combination with gradient checkpointing and DDP. But I am not entirely sure, as the errors are not always very illustrative.
> 
>     * When I use **1 GPU** and **no DDP** and **weight sharing**, the gradient checkpointing works fine and increases my batch size from 3 to 20!
> 
>     * When I use **4 GPUs** and **DDP** and **no weight sharing**, the gradient checkpointing works (with `find_unused_parameters=False` and returning only the `loss` from `forward`) and that allows me to use a batch size of 8 (so effectively 32)
> 
>     * When I try to **2 GPUs** and **DDP** and **weight sharing**, the following error is thrown:
> 
> 
> ```
> RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 
> 1) Use of a module parameter outside the forward function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes
> 2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple checkpoint functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases yet.
> 3) Incorrect unused parameter detection. The return value of the forward function is inspected by the distributed data parallel wrapper to figure out if any of the module's parameters went unused. For unused parameters, DDP would not expect gradients from then. However, if an unused parameter becomes part of the autograd graph at a later point in time (e.g., in a reentrant backward when using checkpoint), the gradient will show up unexpectedly. If all parameters in the model participate in the backward pass, you can disable unused parameter detection by passing the keyword argument find_unused_parameters=False to torch.nn.parallel.DistributedDataParallel.
> ```
> 
> **MY QUESTION IS: Is this expected? Does weight sharing fall in category 2 of this Error message?**
> 
> It would be great to leverage the benefits of **DDP**, **multi-GPU**, **gradient checkpointing** and **weight sharing**, but I am just not sure whether that is possible.

Hi Claartje,

I met the same problem. Have you solved it?

**Comment by JiexingQi** [comment]
Hi，@ @moscow25 I also face this problem when i use t5 model in DDP mode and set gradient_checkpointing=True. I find it will consume very more GPU memory than use single GPU when set gradient_checkpointing when batch_per_device is equal. Have you met this problem and any comment for this? Thank you!

**Comment by entslscheia** [comment]
I've basically exhausted all possible ways but still could not find a solution for using HuggingFace T5 with gradient checkpointing plus DDP. I am pretty sure there is no unused parameters in my model, and I also tried to do `_set_static_graph()`, but looks like it does not work for T5. Very frustrated..Sigh..
