### ISSUE TITLE
What should I pass as model_path to scripts.triviaqa

### ISSUE THREAD

**Issue by roastduck** [allenai/longformer#68]
I tried to run the pre-trained model as per `cheatsheet.txt`, in which the `model_path` argument should be `path/to/pretrained/longformer-large-4096`. What is this file? I used `allenai/longformer-large-4096` from [https://huggingface.co/models](https://huggingface.co/models), but got the following error:

```
python -m scripts.triviaqa  --train_dataset data/squad-wikipedia-train-4096.json  --dev_dataset data/squad-wikipedia-dev-4096.json  --gpus 0  --num_workers 4 --max_seq_len 4096 --doc_stride -1  --save_prefix model/triviaqa-longformer-large  --model_path allenai/longformer-large-4096  --test
Traceback (most recent call last):
  File "/home/rd/install/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-7.3.0/python-3.7.0-5vsakxo7t7c3jona2og2myyjwydkkg6c/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/rd/install/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-7.3.0/python-3.7.0-5vsakxo7t7c3jona2og2myyjwydkkg6c/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rd/src/longformer/scripts/triviaqa.py", line 702, in <module>
    main(args)
  File "/home/rd/src/longformer/scripts/triviaqa.py", line 658, in main
    model = TriviaQA(args)
  File "/home/rd/src/longformer/scripts/triviaqa.py", line 260, in __init__
    self.model = self.load_model()
  File "/home/rd/src/longformer/scripts/triviaqa.py", line 266, in load_model
    model = Longformer.from_pretrained(self.args.model_path)
  File "/home/rd/.local/lib/python3.7/site-packages/transformers/modeling_utils.py", line 655, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/home/rd/src/longformer/longformer/longformer.py", line 18, in __init__
    layer.attention.self = LongformerSelfAttention(config, layer_id=i)
  File "/home/rd/src/longformer/longformer/longformer.py", line 78, in __init__
    self.attention_dilation = config.attention_dilation[self.layer_id]
AttributeError: 'RobertaConfig' object has no attribute 'attention_dilation'
```

**Comment by roastduck** [comment]
I have figured it out. Maybe the model at huggingface.co is out of date. Using the model directly from the link at README.md solved the problem.

**Comment by ibeltagy** [comment]
There are small differences between the config and model implementations between here and the one in the HF repo.
