### ISSUE TITLE
pytorch_lightning related error testing triviaqa.py

### ISSUE THREAD

**Issue by arashashari** [allenai/longformer#79]
Following the [cheat-sheet](https://github.com/allenai/longformer/blob/master/scripts/cheatsheet.txt#L45-L52), I am testing the triviaqa code for pre-training. 
(Note: "max_nb_epochs" needs to be changed to "max_epochs")

While doing that, I ma getting the following pytorch-lightning related error:

Traceback (most recent call last):
  File "triviaqa.py", line 704, in <module>
    main(args)
  File "triviaqa.py", line 696, in main
    trainer.fit(model)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 952, in fit
    self.ddp_train(task, model)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/distrib_data_parallel.py", line 538, in ddp_train
    self.run_pretrain_routine(model)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 1156, in run_pretrain_routine
    self.train()
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py", line 370, in train
    self.run_training_epoch()
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py", line 452, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py", line 657, in run_training_batch
    grad_norm_dic = self.run_batch_backward_pass(split_batch, batch_idx, opt_idx, optimizer)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py", line 709, in run_batch_backward_pass
    self.call_optimizer_step(optimizer, opt_idx, batch_idx, split_batch)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py", line 747, in call_optimizer_step
    using_native_amp=native_amp)
TypeError: optimizer_step() got an unexpected keyword argument '**using_native_amp**'

I wonder if you have seen this before /can comment on this.

Spec: Python 3.6.9, v100-smx2 GPU, Cuda 10.1, torch 1.5, transformer 2.11, pytorch-lightning 0.6.0

**Comment by ibeltagy** [comment]
I thought `pytorch-lightning 0.6.0` doesn't know about `using_native_amp`. Can you double-check the pytorch-lighting version you have?

**Comment by arashashari** [comment]
Just double checked, and I was using 0.6.0.
After upgrade still saw the issue. However, 
- uninstalled pytorch-lightning,
- removed all related files under /usr/local/lib/python3.6/dist-packages/pytorch_lightning*,
- and installed again
and interestingly, this time it works :)
Thannks
